name: 'Remove a Release Asset'
description: 'Remove a release asset from an existing release in your repository'
author: 'flcdrg'
inputs:
  release_id:
    description: 'The release id to remove asset from'
    required: true
  asset_name:
    description: 'The name of the asset you want to remove'
    required: true

runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'package'
  color: 'gray-dark'
