# Auto-merge dependabot pull requests that pass all checks
name: Auto-merge Dependabot PRs

on:
  workflow_dispatch:
  schedule:
    - cron: "0/30 * * * *" # Every 30 minutes
    
jobs:
  test:
    name: Auto-merge minor and patch updates
    runs-on: ubuntu-latest
    steps:
      - uses: koj-co/dependabot-pr-action@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          merge-minor: true
          merge-patch: true