# Auto-merge dependabot pull requests that pass all checks
name: auto-merge

on:
  pull_request:

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Dependabot Auto Merge
        uses: ahmadnassri/action-dependabot-auto-merge@v2.3.1
        with:
          target: minor
          github-token: ${{ secrets.PAT_REPO_FULL }}