name: "CI"

on:
  pull_request:
  push:
    branches:         # array of glob patterns matching against refs/heads. Optional; defaults to all
      - master          # triggers on pushes that contain changes in master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install

      - run: npm run all      

      - name: Release & Assets
        id: create-test-release
        uses: Hs1r1us/Release-AIO@v1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}        
        with:
          tag_name: ${{ github.ref }}
          asset_files: package.json
          draft: true
          prerelease: true
                    
      - name: Test action
        uses: ./ # Uses an action in the root directory
        id: remove
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_id: ${{ steps.create-test-release.outputs.id }}
          asset_name: package.json

      - name: Delete test release
        if: ${{ always() }}
        uses: liudonghua123/delete-release-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_id: ${{ steps.create-test-release.outputs.id }}
          # Whether suppress errors or not
          suppress_errors: false

  # Job to create/update the latest release draft. Only run for 'main' branch builds
  update_release_draft:
    name: Update release draft
    runs-on: ubuntu-latest
    needs: [test]

    if: github.ref == 'refs/heads/master'
    steps:
        
      - uses: release-drafter/release-drafter@v5
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
