name: "Main"

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - run: npm install

      - run: npm run all

  # Job to create/update the latest release draft. Only run for 'main' branch builds
  update_release_draft:
    name: Update release draft
    runs-on: ubuntu-latest
    needs: [test]

    if: github.ref == 'refs/heads/master'
    steps:
        
      - uses: release-drafter/release-drafter@v5
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}